language: node_js
node_js:
- stable
before_install: cd www
before_deploy: cd ..
deploy:
  - provider: script
    script: npm install -g now && now --token=$NOW_TOKEN && now --token=$NOW_TOKEN alias s.cserdean.com
    on:
      branch: master
  - provider: script
    script: npm install -g now && now --token=$NOW_TOKEN && now --token=$NOW_TOKEN alias dev.s.cserdean.com
    on:
      branch: dev
